### ISSUE TITLE
Gerber rotation, arcs

### ISSUE THREAD

**Issue by luftek** [ThisIsNotRocketScience/GerberTools#1]
When rotating gerbers, some arcs act funny
I have arcs on Silkscreen and Soldermask

90° NOT ok
![combined_test_combined_bottom](https://cloud.githubusercontent.com/assets/1379063/20444659/38f6962c-add2-11e6-964b-2e9ed7cc68e5.png)

0° OK
![combined_test_combined_bottom](https://cloud.githubusercontent.com/assets/1379063/20444788/bcaaeafe-add2-11e6-943f-e020abce51f6.png)

**Comment by StijnKuipers** [comment]
![luftekrotation](https://cloud.githubusercontent.com/assets/205945/20452256/9d45af2c-ae05-11e6-8a3d-29e67a54e3c9.jpg)
Hows this?

**Comment by luftek** [comment]
847559f
