### ISSUE TITLE
Additional Milling added (makes a triangle from an curved line)

### ISSUE THREAD

**Issue by ranseyer** [ThisIsNotRocketScience/GerberTools#103]
The gerbertools add an additional line from the beginning bi to the end of the line to a curved milling.
The original line has a width of 50 mil, and the added line (width 0mil) creates an area similar to a triangle.

I woul be happy abou an help or an hint...

[merged-defect.zip](https://github.com/ThisIsNotRocketScience/GerberTools/files/4172315/merged-defect.zip)

![G1_Combined_Top](https://user-images.githubusercontent.com/3889328/74055033-7b191f00-49df-11ea-87e9-70bae8d7235c.png)

[Original-Gerber-HM-Relais4-flach-v01-034-eagle7.zip](https://github.com/ThisIsNotRocketScience/GerberTools/files/4172324/Original-Gerber-HM-Relais4-flach-v01-034-eagle7.zip)

**Comment by StijnKuipers** [comment]
Could you also post the original file? Can't say much about the error on
the combined file alone.

**Comment by ranseyer** [comment]
Yes, it is attached above as: Original-Gerber-HM-Relais4-flach-v01-034-eagle7.zip

**Comment by ranseyer** [comment]
I can attach it again i needed.

**Comment by StijnKuipers** [comment]
Oh right - github mail only showed 1 of 2 links

**Comment by StijnKuipers** [comment]
Your GML file has a random unclosed line in the middle - fix that in your eagle file and reexport.

**Comment by StijnKuipers** [comment]
![image](https://user-images.githubusercontent.com/205945/74778027-09708900-529b-11ea-9ec7-29d61ebfc1c7.png)

**Comment by ranseyer** [comment]
Hmm, this is on the milling layer. 

In the past i ordered exactly in this way PCBs and the producers milled it exactly as wide as in eagle designed.

But i learned the i can redraw this with an line wideness of 0mil ... 
Thanks for the feedback !

**Comment by StijnKuipers** [comment]
a lot of boardhouses have teams of people manually fixing boards without
telling you about this... "magic happens"

These gerber tools dont have the luxury of interpretation :-(
