### ISSUE TITLE
Solder mask, silkscreen and solderpaste are missing after using panelizer tool

### ISSUE THREAD

**Issue by azrilhafizi** [ThisIsNotRocketScience/GerberTools#134]
I try to merge together a few board by using the panelizer  tool, but the solder mask, silkscreen and solderpaste are missing from the output. The Gerber Viewer tool display the board correctly.
![led_2021-03-09_Combined_Bottom](https://user-images.githubusercontent.com/55910056/110435927-937dd080-80ee-11eb-8b60-3766f019c75b.png)
![led_2021-03-09_Combined_Top](https://user-images.githubusercontent.com/55910056/110435932-94aefd80-80ee-11eb-85b0-11e3ad2b0bfd.png)

Output from Eagle
![Capture](https://user-images.githubusercontent.com/55910056/110436010-ad1f1800-80ee-11eb-9681-d08fce24f673.JPG)

Output from Gerber Panelizer 
![Capture1](https://user-images.githubusercontent.com/55910056/110436059-b9a37080-80ee-11eb-8cc8-3a6a3108a5b3.JPG)

**Comment by azrilhafizi** [comment]
I figured it out. New version of Eagle changed the output format, so Panelizer would not recognized it. Using https://github.com/StanislavJochman/GerberTools_Eagle_Fix I managed to fix it

**Comment by MayckonJhonatas** [comment]
hi, did you fixed it? i'm having the same problem.
