### ISSUE TITLE
Feature Req: in Panelizer, crop silkscreen beyond board outline

### ISSUE THREAD

**Issue by thatch** [ThisIsNotRocketScience/GerberTools#19]
Right now it leaks from one board to another if it extends more than the gap between them.  (Yes, I know, fix the footprint.)

**Comment by StijnKuipers** [comment]
Already fixed in latest version - there is a checkbox to enable this in board properties. Personally I actively use overlapping silk to make panelwide art merge in - so I left it as an option.
