### ISSUE TITLE
Outline problem (release 2016-11-28, your blog) 

### ISSUE THREAD

**Issue by luftek** [ThisIsNotRocketScience/GerberTools#2]
![image](https://cloud.githubusercontent.com/assets/1379063/20682309/c4d00570-b5a7-11e6-82c3-a8329eea6096.png)

I use same Gerbers as previous time.

**Comment by StijnKuipers** [comment]
Which build exactly did you try this on? Latest one I just uploaded?

**Comment by StijnKuipers** [comment]
Oh right - let me check. 

Is the generated output correct?

**Comment by StijnKuipers** [comment]
Right... silly regression in the outline builder

**Comment by StijnKuipers** [comment]
Found it - uploading fix!

**Comment by luftek** [comment]
thanks, works smoother also
