### ISSUE TITLE
.gm1 file generated even though software doesn't seem to know anything about them

### ISSUE THREAD

**Issue by CRImier** [ThisIsNotRocketScience/GerberTools#24]
So I have both .gm1 and .gml files in my gerber folder, for a board I have 14 copies of (on 10x10 cm panel). I generate the panel, and I get both .gm1 and .gml in the output folder. This is not a bug, but I'm curious - how, and why, does that work? =)

**Comment by StijnKuipers** [comment]
All the file types are merged seperately - it does not try to guess what layer something is because there are so many dialects/options there

If you have .layer files in the source folder - it will create a .layer file in the output.
