### ISSUE TITLE
GerberPanelizer wouldn't compile for me until I changed one definition

### ISSUE THREAD

**Issue by CRImier** [ThisIsNotRocketScience/GerberTools#25]
I'm using Visual Studio 2015 Community edition. [Here's the line that wouldn't compile for me.]( https://github.com/ThisIsNotRocketScience/GerberTools/blob/master/GerberPanelizer/GLGraphicsInterface.cs#L182) The workaround was replacing it with this block of code:

```
       public bool Dotted {
            get
            {
                throw new NotImplementedException();
            }

            set
            {
                throw new NotImplementedException();
            }
        }
```

**Comment by StijnKuipers** [comment]
thanks! added - I'm on the more modern VS myself - didnt notice :-)
