### ISSUE TITLE
Gernerate single drill file only

### ISSUE THREAD

**Issue by TheNitek** [ThisIsNotRocketScience/GerberTools#29]
As far as I understood the Panelizer is currently creating 2 drill files (combined.drl and combined.txt). Most services seem to honor only one of those files (I'm right now waiting for a dirtypcb order where I realized to late that, at least in the preview, only the combined.txt holes seem to be made :( ). Would be nice to have an option to have both files merged to prevent any issues like this.

**Comment by luftek** [comment]
F**k, already in Production at DirtyPCB and not even ordering for myself

**Comment by TheNitek** [comment]
I'm not sure yet that this is really an issue with DirtyPCB, might just be the preview!

**Comment by luftek** [comment]
Hopefully, Requested them to make photos before sending. Hopefully they do respond with photos.

**Comment by TheNitek** [comment]
Did your panels (or pictures) arrive? Any real issues?

**Comment by luftek** [comment]
Everything OK. No problem with production.

**Comment by TheNitek** [comment]
I can confirm it worked with dirtypcbs (even though the preview was wrong/incomplete). Still for other services it would be great to have this option.

**Comment by luftek** [comment]
I have used panelizer for JLCPCB and no problems with this issue "dual files"
Close the issue?
