### ISSUE TITLE
line widths

### ISSUE THREAD

**Issue by luftek** [ThisIsNotRocketScience/GerberTools#3]
Sorry, me again :) 👍

Line widths are messed sometimes. By deleting instances of Gerbers and placing them again something changes. Seems it is not 100% reproducable.

Any changes in xml format from last versions?
How could number of instances affect line width? (not including "your" tabs)
Photos before - max. number of instances 4
Last photo is OK - max. number of instances 3

Maybe make About page COPY/PASTEABLE for bugs sake, photo for now
![image](https://cloud.githubusercontent.com/assets/1379063/20764268/c755ccee-b72d-11e6-85e6-7c9336aa7c75.png)

![image](https://cloud.githubusercontent.com/assets/1379063/20765004/e9dc9f88-b730-11e6-81ee-9187abbae7a2.png)
![image](https://cloud.githubusercontent.com/assets/1379063/20765010/f10921d2-b730-11e6-86fe-96bdc6af4077.png)
![image](https://cloud.githubusercontent.com/assets/1379063/20765021/fb7b6832-b730-11e6-9b69-1f1ee7cd78cd.png)

**Comment by StijnKuipers** [comment]
Usually this means the final command in the previous gerber leaves something open - or a state is not correctly reset - Merging this state will then propagate on... or maybe the initial aperture is not selected correctly.  Could you mail me these 3 gerbersets so I can prod them around? - this seems like a nicely isolated testcase. 

I will also make an easier-to-copy aboutbox.

**Comment by luftek** [comment]
it is 6 gerbers and gerberset.
gerberset will need a change if you want to use (fixed folder paths)
https://github.com/luftek/LimeSDR-USB/tree/master/hardware/plug/1v2/Enclosure/0v6_76x35/panel/_Gerber/20161104_combined 

download https://github.com/luftek/LimeSDR-USB/tree/master/hardware/plug/1v2/Enclosure 
with: https://minhaskamal.github.io/DownGit/#/home

**Comment by StijnKuipers** [comment]
Thankyou! - will dive in to this tonight.
I'm aware of the relative path issue - I'll give that some attention soon as well

The aboutbox has been fixed btw

**Comment by luftek** [comment]
I watch the progress, have an app on phone :) thank you for this

**Comment by StijnKuipers** [comment]
Ok - turned out to be something else. There was a special path for "massive merges" that wasnt tested very well - in the cases I tried (many instances of the same board) - this was no issue - but for 8+ different board designs some of the apertures got mixed up. Should be correct now.

**Comment by luftek** [comment]
Awesome, that you found it

**Comment by StijnKuipers** [comment]
Build updated on thisisnotrocketscience.nl!
