### ISSUE TITLE
Bug: oval through-hole

### ISSUE THREAD

**Issue by fastlink30** [ThisIsNotRocketScience/GerberTools#36]
if  component pin is through-hole with shape oval and drill is oval, output gerber hole is not made!
Version 1.0.6257.24941 built on 17/02/2017 

![1](https://user-images.githubusercontent.com/9497088/29749930-c27adaec-8b36-11e7-9e7a-b744b2b4772f.png)
![2](https://user-images.githubusercontent.com/9497088/29749931-c27e609a-8b36-11e7-8176-71b218aa82b0.png)
![3](https://user-images.githubusercontent.com/9497088/29749932-c27f2b24-8b36-11e7-8a7a-79d92690e0a5.png)

**Comment by thatch** [comment]
I actually just came here to report the same issue in the Panelizer.  Here's a simple repro (look at J1); I don't recall what version I'm using but can check.

[plated_slots_test-fab.zip](https://github.com/ThisIsNotRocketScience/GerberTools/files/1279137/plated_slots_test-fab.zip)

I looked at the resulting gerbers, and there are some odd overlapping drills at 0,0 only on boards that had "oval" holes.

**Comment by fastlink30** [comment]
in the last update 1/11 the problem remain, for me this is a big problem, i can't publish on dirtypcb

**Comment by chaosAD** [comment]
I was about to raise this issue when I bumped into this one. Any chance this is going to be fixed?

**Comment by bjpirt** [comment]
I've just run across this issue when using a build from HEAD - would be great to be able to use oval holes

**Comment by DIYglenn** [comment]
Seeing the same now in my issue:
[Missing drill holes](https://github.com/ThisIsNotRocketScience/GerberTools/issues/49)

**Comment by tfuhub** [comment]
I think this is a bug that does not handle decimal-point. Try this patch:
```
--- E:\GerberTools-2018-08-10\GerberLibrary\Core\GerberSplitter.cs	Sat Jul 14 15:51:08 2018
+++ E:\GerberTools-2018-08-10_patch\GerberLibrary\Core\GerberSplitter.cs	Thu Sep 20 10:45:04 2018
@@ -263 +263 @@ namespace GerberLibrary
-                    if (char.IsNumber(current) || current == '+' || current == '-')
+                    if (char.IsNumber(current) || current == '+' || current == '-' || (hasdecimalpoint && current == '.'))
```

**Comment by fastlink30** [comment]
downloaded & recompiled project (triangle library is not present, i must search the source)

anyway confirmed, with the patch proposed i see the oval holes! :) ... finally..... i can re-start use this tool

thanks!

**Comment by ZericE** [comment]
I just recompiled (v1.0.7125.30657) and am still having issues with oval holes.  Instead of one oval hole, I'm getting two round holes next to each other.  I'm using kicad, and it's output looks correct from the gerber viewer. Is there some other trick I'm missing?
![2019-07-05_143234](https://user-images.githubusercontent.com/38921404/60749097-057d3a00-9f4a-11e9-94ad-8e0744eac3a9.jpg)

**Comment by andreq** [comment]
@ZericE dunno if you ever found the solution, but in Kicad when you generate drill file switch from "Use router command" to "User alternate drill mode". 

I have to compile latest code + change that in Kicad to get proper oval holes. Would be nice if the library would support G00 command.

**Comment by ZericE** [comment]
@andreq Thanks, I will try changing the drill setting in kicad on my next batch.  For the project I was working on I just had the PCB vendor deal with it.

**Comment by Shackmeister** [comment]
Added a PR for G00 and G01 support, so the "User alternate drill mode" is not needed
https://github.com/ThisIsNotRocketScience/GerberTools/pull/102
