### ISSUE TITLE
File error? 

### ISSUE THREAD

**Issue by DaveCalaway** [ThisIsNotRocketScience/GerberTools#46]
When i put the Gerber files inside the program, nothing appears. 
What i wrong? 
I used the new version of eagle. I was try the extension .gbr but i received the same result. 
![img_20180205_193736](https://user-images.githubusercontent.com/10884164/35822468-abc35ed2-0aac-11e8-84d5-b18a4fdf520d.jpg)

**Comment by RandomWon** [comment]
I think this is because your gerber contains a .GM1 file

**Comment by marmue** [comment]
Hi Dave,

not sure if this is a bug, but I noticed that some of my exported gerber work and some not. I used different programs and also same, like eagle. For one export it works for another not.

I found that the working gerber do not have any special aperture like %ADD11R,0.05721X0.02375*%
Maybe this is the problem, as it might not be supported?

Best regards
Marco

**Comment by luftek** [comment]
Any progress? Close issue?

**Comment by StanislavJochman** [comment]
Hello I found solution. I described it here #93
