### ISSUE TITLE
Can we have an updated release?

### ISSUE THREAD

**Issue by mundodisco8** [ThisIsNotRocketScience/GerberTools#50]
Hi,

I don't program in C#, so I was wondering if it would be possible to get an updated build. I see that there's been a lot of movement since the last release, and I understand that your time is limited and might be busy with life, so no probs if you are busy or thinking on getting some other stuff before releasing.

Cheers!

**Comment by StijnKuipers** [comment]
Added one!

**Comment by StijnKuipers** [comment]
Indeed incredibly busy - we are still gearing up our synthesizer brand with the TiNRS team. Lots of custom tooling for this project, but not really for general consumption as of yet.
