### ISSUE TITLE
Kicad 5

### ISSUE THREAD

**Issue by DaveCalaway** [ThisIsNotRocketScience/GerberTools#54]
Hi everyone,
I'm using the kicad 5 version and when i plot the gerber files i see that the all files has the extansions ".GBR".

So using this guide, i see the extensions in kicad: https://goo.gl/PiiejM
Now i saved the gerber files in this "old" configuration, but nothing works....

![screen shot 2018-08-05 at 18 33 46](https://user-images.githubusercontent.com/10884164/43687887-29e57204-98de-11e8-8520-0dbfb3ed4424.png)

**Comment by luftek** [comment]
- Replace file ending with .gm1 with .gko
What does not work? I use Kicad v5 and it works as expected

**Comment by DaveCalaway** [comment]
>  Replace outline file extension .gm1 with .gko   

Yep, done, but does not work.

This is the error:
![1](https://user-images.githubusercontent.com/10884164/43688542-ff124f2c-98ea-11e8-9b5c-3f56ac4ca8ca.png)

> Do you use auxiliary axis in KiCad? recommend!

I think this is only recommended, right?

**Comment by luftek** [comment]
- Operating system?
- what happens if you press Continue?

Save error message in .txt file and append here.
If gerbers are not a secret also append

**Comment by DaveCalaway** [comment]
> OS:

 Win 10 Home 64 bit

> GerberViewer:

 i don't know, i tried to load in different web Gerber and JLCPCB and it has not problem.

> what happens if you press Continue?:

Here is the error: https://pastebin.com/0ZY7kxkz
If i press continue the program print a big X like my last screenshot.

**Comment by luftek** [comment]
Days ago I used panelizer with JLCPCB service, no problem.
Prepare simple gerber files with your flow that you can share.

**Comment by DaveCalaway** [comment]
Same problem with GerberTools...
No problems with JLCPCB.
[gerber.zip](https://github.com/ThisIsNotRocketScience/GerberTools/files/2260640/gerber.zip)

**Comment by luftek** [comment]
I tried with your gerbers. No issue. I append a working setup.
![2018-08-06 01_01_35-this is not rocket science - gerber panelizer - set_ set](https://user-images.githubusercontent.com/1379063/43692165-7e4a1876-9925-11e8-9129-ec2fc69b582b.png)

Remark:
- auxiliary coordinates would make thing show up immidiately (current offset is in range of 150mm both axis)
- in KiCad I always select to combine NPTH/PTH holes in one .drl  (as per JLCPCB request/spec)

TEST:
For ease of use 
unpack Panelizer.zip in C:\ folder
run panelizer.exe
-> File/Open -> select C:\Panelizer\gerber\set.gerberset

Photos:


![2018-08-06 01_07_36-panelizer](https://user-images.githubusercontent.com/1379063/43692211-f2240fea-9925-11e8-9dc2-f861db1c984b.png)

**Comment by luftek** [comment]
Please also check issue #21 for possible solutions.

**Comment by DaveCalaway** [comment]
With this solution, https://github.com/ThisIsNotRocketScience/GerberTools/issues/21#issuecomment-339008902 , it's works! I used the original Panelizer not your.
I try to upload the gerber file to JLCPCB, but now it does not show me the preview.
This is the result, is it ok?
![untitled_combined_bottom](https://user-images.githubusercontent.com/10884164/43715372-9d4b97f8-9980-11e8-9814-50a9650f84c5.png)
![untitled_combined_top](https://user-images.githubusercontent.com/10884164/43715373-9d679cf0-9980-11e8-8d06-5e9a1b48792e.png)
