### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by deece** [ThisIsNotRocketScience/GerberTools#62]
Some instructions on how to build this ourselves would be nice.

Things that I spent time on:
  - What is releasebuilder?
  - Where to find Triangle.NET & how to update the references
  - How to build the projects such that they run

**Comment by TheReelDill** [comment]
+1
Have installed Visual Studio 2017, but do not know how to compile successfully. 
I wanted to create a binary that includes the fix suggest in [issue 52](https://github.com/ThisIsNotRocketScience/GerberTools/issues/52#issue-347259083)
