### ISSUE TITLE
New version, rendering: Panelizer vs. QuickRender

### ISSUE THREAD

**Issue by luftek** [ThisIsNotRocketScience/GerberTools#7]
http://blog.thisisnotrocketscience.nl/wp-content/uploads/2015/02/2017-01-17-PanelTools.zip
Looks like something to do with circles

![image](https://cloud.githubusercontent.com/assets/1379063/22176767/84d9f95a-e011-11e6-9f8a-e8d2e75c47b6.png)

**Comment by StijnKuipers** [comment]
Ive noticed a few odd regressions with the renderer called from the Panelizer - could you send me this file to test?

**Comment by luftek** [comment]
[gerbers.zip](https://github.com/ThisIsNotRocketScience/GerberTools/files/724521/gerbers.zip)
Change file paths in *.gerberset

**Comment by StijnKuipers** [comment]
Fixed! Rendergeometry scaling got hit by a premature optimization -> the circles ended up with 0 vertices due to a far too low geometry setting with no sanity checking. 

Will upload new build today!

**Comment by StijnKuipers** [comment]
Added a new GitHub release! From now on the updates shall be packaged here

**Comment by luftek** [comment]
Thank you! Managing releases here is awesome 👍
