### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by deece** [ThisIsNotRocketScience/GerberTools#73]
@StijnKuipers With all the fixes that have been merged, a new release would be useful :) (hopefully you have time)

I think I fixed the bad package hint paths that required this in your environment: 7af196ab98ed27396be88d2f42999f20badfcc75

**Comment by TheReelDill** [comment]
+1 for that.

**Comment by andreq** [comment]
+1, would be nice not to have to compile the whole thing to get Panelizer kicad slot fixes :)

**Comment by mplacona** [comment]
I am trying to compile this but can't! Can anyone please send me their compiled version? Thanks!

**Comment by deece** [comment]
Latest release is here: https://github.com/ThisIsNotRocketScience/GerberTools/releases/tag/20-09-2019

**Comment by mplacona** [comment]
Yeah, I’ve seen that. But with it being from September, it doesn’t have the fix you did in November which seems to address the problem I am having with fill empty area.

Would appreciate if you could send me a new release. 

Thanks

**Comment by deece** [comment]
Ah, @StijnKuipers will have to help with that.

**Comment by StijnKuipers** [comment]
Uploading.

**Comment by StijnKuipers** [comment]
https://github.com/ThisIsNotRocketScience/GerberTools/releases/tag/July2020

**Comment by mplacona** [comment]
Totally solves the problem.

Thank you so much!
