### ISSUE TITLE
Panelizer: how to open KiCad gerbers

### ISSUE THREAD

**Issue by rusefi** [ThisIsNotRocketScience/GerberTools#9]
I have a folder with my gerbers geberated by KiCad - for example uncompressed https://svn.code.sf.net/p/rusefi/code/trunk/hardware/brain_board/gerber/brain_board_STM32F407_R0.2.zip

I launch GerberTools_2017_1_27\Panelizer\GerberPanelizer_VS2015.exe and then what?

I do not have a .gerberset file - how do I create one?

I try opening my gerbers one by one but nothing is rendered. Please help.

**Comment by luftek** [comment]
Did you change .gm1 outlinr file to .gko?

**Comment by rusefi** [comment]
I have not changed .gm1 outlinr file to .gko, I did not know I needed to?

Assuming I should have renamed it, I have renamed my .gm1 to .gko but nothing seems to have changed - still cannot open individual files, still no idea about gerbersets

if that would help I am trying to open https://svn.code.sf.net/p/rusefi/code/trunk/hardware/rusefi_hardware_history/brain_board_SD_Card_1_rev00.10/gerber/brain_board_SD_Card_1_R0.01.zip (an uncompressed version of that file)

**Comment by luftek** [comment]
Ok, you renamed .gm1 to .gko

Then:
1. Open Panelizer
2. Edit -> New
3. Board Placement -> Add Gerber Folder
4. For multiple instances of same gerber file click on instance in the right tree
5. Probably (0,0) coordinates (auxiliary axis) is not assigned on board edge so use: Board Placement -> Autopack:Naive

Other things are up to you to discover ;)

![bla](https://cloud.githubusercontent.com/assets/1379063/22660107/9927af06-eca0-11e6-890d-7997f8eae724.png)

**Comment by luftek** [comment]
About the auxiliary axis for easier board placement in the future:
![bla2](https://cloud.githubusercontent.com/assets/1379063/22660449/e2b5f550-eca1-11e6-875b-2a0f204d1214.png)
![bla3](https://cloud.githubusercontent.com/assets/1379063/22660462/eb11c7d8-eca1-11e6-92b5-9573b42c1135.png)
![bla4](https://cloud.githubusercontent.com/assets/1379063/22660472/f544401e-eca1-11e6-81fd-bd1b2a92a160.png)

**Comment by StijnKuipers** [comment]
The concept is to add entire folders in 1 go - you cannot add individual gerber files.


Process is roughly:

1) start the .exe
2) drag the folders you want to the main area
3) a new panel document will start with 1 instance for each folder you dragged on to the area.
4) you can add more instances (rightclick menu) / save the current setup / move stuff around
5) export merged.

There are some notes in the included documentation - the layer-names roughly follow the defacto standards (see OSHPark, Seeed, PCBWay or DirtyPCBs etc)
