### ISSUE TITLE
Spurious extra circular tracks on inner layers

### ISSUE THREAD

**Issue by Gasman2014** [ThisIsNotRocketScience/GerberTools#91]
Using this to panellise some Gerbers created with Kicad using  version 1.0.6345.32009 on W7 running on a VirtualBox. The gerber files include some circular tracks. The gerbers look correct (in two different viewers) prior to panelisation, however, after panelisation, weird circular artefacts on the two inner copper layer are apparent. Initially the circular cutout was defined as a circle but I have replaced this and all other arcs of >180º with arcs of < 180º as I believe that circular gerber tracks have been problematic in certain situations.
My primary pc is a mac so am running this in virtualisation but don't think this should be an issue. I am prepared to try building this from a newer version if this will address the issue but I am unclear if it will help. A newer binary edition would be very helpful. 

After panelisation:
![Screen Shot 2019-05-31 at 13 56 40](https://user-images.githubusercontent.com/8401593/58710884-44512a80-83b5-11e9-940d-43145eb9cc0a.png)

Gerber view in 'Cuprum'
![Screen Shot 2019-05-31 at 15 06 43](https://user-images.githubusercontent.com/8401593/58711159-ca6d7100-83b5-11e9-94af-a26ce117b2c8.png)

Gerber view in 'gerbview'
![Screen Shot 2019-05-31 at 14 00 12](https://user-images.githubusercontent.com/8401593/58710886-44512a80-83b5-11e9-8f17-987929a9e88b.png)

**Comment by Gasman2014** [comment]
For completeness, I ensured .gm1 was renamed to .gko, used protel extensions and added and used an auxiliary axis to ensure the source Gerbers were compliant with GerberPanelizer. I am happy to share the source and output gerbers if that is of any help.

**Comment by bzroom** [comment]
@Gasman2014 , did you ever find a solution or workaround to gerber panelizer?

**Comment by Gasman2014** [comment]
This was only intended as a small batch run but thought I could get more out of the batch if I panelized them myself. In the end I just got the fab to panelize them for me.
I have used this software successfully before but I would really prefer a macOS solution. I have used a java app with Kicad which works OK but can't put my finger on it right now.

**Comment by StijnKuipers** [comment]
hmm missed this one - any chance on getting some gerber files to check with?

**Comment by bzroom** [comment]
Please see my issue here:
https://github.com/ThisIsNotRocketScience/GerberTools/issues/108

I attached gerbers there, I think it's a similar problem.

I retried with my new board and the latest version of Panelizer. The result
was different but still broken. It seems like copper fill areas do not
respect if there is a hole inside the copper fill. In my example gebers,
there is a drill hole in the board outline, but the copper area fills over
the whole area. The copper area also fills over traces that are inside the
area. It's not subtracting islands for board holes or even internal traces
within the profile.

Thank you!

**Comment by bzroom** [comment]
[image: image.png]

**Comment by Gasman2014** [comment]
I would be happy to share the original gerbers but need to look them out. Had to replace my HDD recently and have not yet reinstalled any virtualisation stuff so can't test them easily but it was a fairly consistent problem with a number of similar designs of different sized round tracks.
