### ISSUE TITLE
Wont work with new vesion of Eagle

### ISSUE THREAD

**Issue by StanislavJochman** [ThisIsNotRocketScience/GerberTools#93]
Hi, 
I recently discovered that Panelizer would not work with the new version of Eagle. New eagle changed the way how they name their files and Panelizer would not read them. After renaming files back to old names everything works so I created this python script which does it automaticaly for you. It uses OS functions so it should work on all operating systems.

https://github.com/StanislavJochman/GerberTools_Eagle_Fix

Best regards Stanley

**Comment by rahmanshaber** [comment]
I am also facing the issue.
Thanks @StanislavJochman  for your script. 
Let's see how pcb look in real life.

**Comment by StijnKuipers** [comment]
New eagle no longer allows you to set up your own job-settings, filenames & target paths?

**Comment by StanislavJochman** [comment]
hello,
i dont know if you can change it but rs274x is commonly used in pcbs
factory and its set es default in eagle so I made this converter which
converts filenames to correct ones.

------------------------------------------------
S pozdravom
StanislavJochman
www.stanislavjochman.sk
Ceo at www.robotcing.sk

**Comment by TimFFischer** [comment]
Thanks @StanislavJochman:
I got inspired and wrote a batch file in order to automatically convert multiple BRD-files to GERBER-files for GerberTools:
[https://wiki.mexle.hs-heilbronn.de/lib/exe/fetch.php?media=convert_brd_to_gerber.rar](url)

Converts all BRD-files in folder "BRD" to GERBER-files in folder "GERBER".
Needs EAGLE 8.6 or higher. Details in readme

**Comment by StanislavJochman** [comment]
@TimFFischer link doesn't work unfortunately.

Best regards StanislavJochman

**Comment by pierow2k** [comment]
> @TimFFischer link doesn't work unfortunately.

@StanislavJochman - The URL works but the link points to the wrong location.  I was able to retrieve the @TimFFischer batch file by copying the URL text and pasting it into a browser.  I think this link should work:

[https://wiki.mexle.hs-heilbronn.de/lib/exe/fetch.php?media=convert_brd_to_gerber.rar](https://wiki.mexle.hs-heilbronn.de/lib/exe/fetch.php?media=convert_brd_to_gerber.rar)

**Comment by StanislavJochman** [comment]
Ok thanks, I will post it here if someone wants it: https://wiki.mexle.hs-heilbronn.de/lib/exe/fetch.php?media=convert_brd_to_gerber.rar

**Comment by Mikegyver** [comment]
> Hi,
> I recently discovered that Panelizer would not work with the new version of Eagle. New eagle changed the way how they name their files and Panelizer would not read them. After renaming files back to old names everything works so I created this python script which does it automaticaly for you. It uses OS functions so it should work on all operating systems.
> 
> https://github.com/StanislavJochman/GerberTools_Eagle_Fix
> 
> Best regards Stanley

hi @StanislavJochman i think your python script did not rename back solderpaste bottom to old name. here is my output when i executed the python script.

![image](https://user-images.githubusercontent.com/16514357/110572917-50c30380-8195-11eb-9c2f-b13ffab3be71.png)

hope this could be fix soon. best regards.

**Comment by StanislavJochman** [comment]
> > Hi,
> > I recently discovered that Panelizer would not work with the new version of Eagle. New eagle changed the way how they name their files and Panelizer would not read them. After renaming files back to old names everything works so I created this python script which does it automaticaly for you. It uses OS functions so it should work on all operating systems.
> > https://github.com/StanislavJochman/GerberTools_Eagle_Fix
> > Best regards Stanley
> 
> hi @StanislavJochman i think your python script did not rename back solderpaste bottom to old name. here is my output when i executed the python script.
> 
> ![image](https://user-images.githubusercontent.com/16514357/110572917-50c30380-8195-11eb-9c2f-b13ffab3be71.png)
> 
> hope this could be fix soon. best regards.

Hi to what name should it be renamed? I did not use the Gerber panelizer for a long time. I can fix that soon if you can tell me to what it should be renamed to.

**Comment by Mikegyver** [comment]
> > > Hi,
> > > I recently discovered that Panelizer would not work with the new version of Eagle. New eagle changed the way how they name their files and Panelizer would not read them. After renaming files back to old names everything works so I created this python script which does it automaticaly for you. It uses OS functions so it should work on all operating systems.
> > > https://github.com/StanislavJochman/GerberTools_Eagle_Fix
> > > Best regards Stanley
> > 
> > 
> > hi @StanislavJochman i think your python script did not rename back solderpaste bottom to old name. here is my output when i executed the python script.
> > ![image](https://user-images.githubusercontent.com/16514357/110572917-50c30380-8195-11eb-9c2f-b13ffab3be71.png)
> > hope this could be fix soon. best regards.
> 
> Hi to what name should it be renamed? I did not use the Gerber panelizer for a long time. I can fix that soon if you can tell me to what it should be renamed to.

it should be rename to .gbp

**Comment by StanislavJochman** [comment]
> .gbp

I hope I fix it you can try to redownload the new script and I would be happy to know if it worked.

Best regards Staney Jochman
